package com.releaseowl.sample.handlers;

import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Map;

import org.springframework.stereotype.Component;

import com.sap.cds.services.EventContext;
import com.sap.cds.services.ErrorStatuses;
import com.sap.cds.services.ServiceException;
import com.sap.cds.services.handler.EventHandler;
import com.sap.cds.services.handler.annotations.On;
import com.sap.cds.services.handler.annotations.ServiceName;

import com.releaseowl.sample.logic.OrderValidator;

/**
 * Handles the stateless OrderService.
 *
 * <p>The Maven sample uses interfaces generated by cds-maven-plugin
 * ({@code cds.gen.*}). SAP publishes no Gradle equivalent of that code
 * generator, so this handler works against the untyped {@link EventContext}
 * instead. The CAP runtime behaves identically - only the compile-time typing
 * is lost.
 */
@Component
@ServiceName("OrderService")
public class OrderServiceHandler implements EventHandler {

	static final String SUBMIT_ORDER = "submitOrder";
	static final String MAX_QUANTITY_PER_ORDER = "maxQuantityPerOrder";

	@On(event = SUBMIT_ORDER)
	public void onSubmitOrder(EventContext context) {
		Integer quantity = asInteger(context.get("quantity"));
		BigDecimal unitPrice = asBigDecimal(context.get("unitPrice"));

		BigDecimal total;
		try {
			total = OrderValidator.totalPrice(quantity, unitPrice);
		} catch (IllegalArgumentException e) {
			throw new ServiceException(ErrorStatuses.BAD_REQUEST, e.getMessage());
		}

		Map<String, Object> confirmation = new HashMap<>();
		confirmation.put("accepted", Boolean.TRUE);
		confirmation.put("quantity", quantity);
		confirmation.put("unitPrice", unitPrice);
		confirmation.put("totalPrice", total);

		context.put("result", confirmation);
		context.setCompleted();
	}

	@On(event = MAX_QUANTITY_PER_ORDER)
	public void onMaxQuantityPerOrder(EventContext context) {
		context.put("result", OrderValidator.MAX_QUANTITY_PER_ORDER);
		context.setCompleted();
	}

	private static Integer asInteger(Object value) {
		if (value == null) {
			return null;
		}
		return value instanceof Number number ? number.intValue() : Integer.valueOf(value.toString());
	}

	private static BigDecimal asBigDecimal(Object value) {
		if (value == null) {
			return null;
		}
		return value instanceof BigDecimal decimal ? decimal : new BigDecimal(value.toString());
	}
}
